---
title: "DATA 413/613 Teaching Website"
author: "David Gerard"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Synopsis

This website contains the teaching materials for DATA 413/613 Data Science, taught at American 
University by [David Gerard](https://dcgerard.github.io/).

# Administrative

- [Syllabus](./admin/syllabus.html)
- [Prerequisites](https://dcgerard.github.io/stat_412_612/): You are expected
  to have already obtained a solid grasp on the materials from Sections 01 to
  09 from my DATA 412/612 teaching website.

# Final Project

- [Final Project Description](./final_project/final_project_description.html)

# Lectures

- 01 Git and the Terminal
    - [01 The Terminal and Bash Basics](./01_git/01_basic_bash.html).
    - [01 Git Setup](./01_git/01_git_setup.html).
    - [01 Git and GitHub](./01_git/01_git_github.html).
    - [01 Git Branches](./01_git/01_git_branch.html).
    - [01 Git Large File Storage](./01_git/01_git_lfs.html).
    - [01 A Quick Introduction to Git and GitHub](https://doi.org/10.1371/journal.pcbi.1004668).
    - [01 Lab: Review of Tidyverse Concepts](https://github.com/data-science-master/lab_01).
- 02 Dates and Times
    - [02 Dates](./02_dates/02_dates.html).
    - [02 Lab](https://github.com/data-science-master/lab_02).
- 03 Vectors and Iteration
    - [03 Vectors](./03_vectors_iterators/03_vectors.html).
    - [03 Iteration](./03_vectors_iterators/03_iterators.html).
    - [03 Lab](https://github.com/data-science-master/lab_03).
- 04 R Packages
    - [04 R Packages](./04_packages/04_packages.html).
    - [04 Unit Testing](./04_packages/04_testing.html).
    - [04 Automated Checks](./04_packages/04_checking.html).
    - [04 Style](./04_packages/04_style.html)
- 05 Web Scraping
    - [05 APIs](./05_web_scraping/05_apis.html).
    - [05 Web Scraping](./05_web_scraping/05_web_scraping.html).
    - [05 Lab](https://github.com/data-science-master/lab_08).
- 06 Shiny Apps
    - [06 Shiny Basics](./06_shiny/06_basic_shiny.html).
    - [06 Layouts](./06_shiny/06_layouts.html).
    - [06 Reactivity](./06_shiny/06_reactivity.html).
    - [06 HTML](./06_shiny/06_html.html).
    - [06 File Uploads](./06_shiny/06_upload.html).
    - [06 Shiny Lab 1: World Bank Data](https://github.com/data-science-master/lab_06_1).
    - [06 Shiny Lab 2: Cereals Data](https://github.com/data-science-master/lab_06_2).
- 09 Introduction to Python
    - [09 Python Setup and Reticulate](./09_python/09_python_setup.html).
    - [09 Numpy](./09_python/09_numpy.html).
    - [09 Pandas](./09_python/09_pandas.html).
    - [09 Matplotlib](./09_python/09_matplotlib.html).
- 10 Personal Websites
    - [10 A Personal Website using Blogdown](./10_websites/10_websites_blogdown.html)
    - [10 A Personal Website using GitHub Pages](./10_websites/10_websites_github.html)
- 11 GNU Make
    - [11 GNU Make](./11_make/11_make.html)
    - [11 Penguins Exercise](https://github.com/data-science-master/penguins)
    - [11 Very Basic Makefile Example](https://github.com/data-science-master/pvalue_sims)
    
- A1 Basic Statistics
    - [A1 Basic Statistics](./A1_basic_stats/A1_basic_stats.html).
    - [A1 Statistical Tests, P-values, Confidence Intervals, and Power: A Guide to Misinterpretations](./A1_basic_stats/greenland_etal_2016.pdf).
    - [A1 Lab](https://github.com/data-science-master/lab_04).
- A2 Linear Models
    - [A2 Simple Linear Regression](./A2_linear_regression/A2_simple_linear_regression.html).
    - [A2 Many Models](./A2_linear_regression/A2_many_models.html).
    - [A2 Lab](https://github.com/data-science-master/lab_05).
- A3 Data.table    
    - [A3 Manipulating Large(ish) Datasets with data.table](./A3_medium_data/A3_medium_data.html).
    - [A3 Lab](https://github.com/data-science-master/lab_07).

# Code of Conduct

Please note that the 'lectures' project is released with a
[Contributor Code of Conduct](CODE_OF_CONDUCT.md).
By contributing to this project, you agree to abide by its terms.
