---
title: "Create your own Website with Markdown"
author: "David Gerard"
date: "`r Sys.Date()`"
output:  
  html_document:
    toc: true
    toc_depth: 4
urlcolor: "blue"
---


```{r setup, include=FALSE}
set.seed(1)
knitr::opts_chunk$set(echo       = TRUE, 
                      fig.height = 3, 
                      fig.width  = 6,
                      fig.align  = "center")
ggplot2::theme_set(ggplot2::theme_bw())
```

# Learning Objectives

- Learn how to create a website with Markdown.
- Create a personal or project website.
- [Setting up a GitHub Pages site with Jekyll](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll)

# Motivation

- **You should have a personal website**
    - Makes you stand out compared to a LinkedIn page that only boring HR folks
      seem to care about.
    - You can post links to class projects and research projects so future
      employers can tell that you're legit.
    - My website is a little outdated (I made it back in grad school), but
      it has still helped me during my career: <https://dcgerard.github.io/>
  
- You can create a project website:
    - This facilitates open-source collaboration between researchers.
    - E.g. I used such a website for notekeeping and collaborating with
      my PI during my postdoc: <http://dcgerard.github.io/succotash_sims/analysis/index.html>

- Other uses:
    - Advertise specific software/papers <https://dcgerard.github.io/updog/>.
    - Create a blog (say, on data science projects) <https://dcgerard.github.io/research/2018/03/16/updog.html>.
    
- We will be using GitHub's [Jekyll](https://jekyllrb.com/) support to create a website. 

- But there is a whole book on how you can create a website using just R and the blogdown package which you might want to check out: <https://bookdown.org/yihui/blogdown/>

# Jekyll

- The full instructions for creating a GitHub pages website using Jekyll is up on GitHub: <https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/setting-up-a-github-pages-site-with-jekyll>

- You should use those instructions if you are creating a new website.

- But we'll go through creating a personal website together so that you can show off your current work.


- On the GitHub repo page for your website, go to Settings > GitHub Pages and select source to be "master". Make sure you click "Save".

- Under Settings > GitHub Pages, GitHub will tell you the URL of your website.

