---
title: "Workflow Tips"
author: "David Gerard"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
urlcolor: "blue"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Learning Objectives

- Improve your remote learning workflow with some tricks and tips.

# Toggling Between Applications

- You will be doing a lot of remote video lectures this semester. 

- So you'll need to have open many applications at the same time. E.g. Zoom, lecture slides, personal notes, R Studio.

- It would be best to have a second monitor, but when I was in college I could only afford a crappy laptop and couldn't pay for a second monitor. So I imagine a lot of you are in the same boat.

- There are two ways I think you can optimize your monitor use

  1. Get really good at toggling between windows using keyboard shortcuts.
  2. Get really good at toggling between multiple desktops using keyboard shortcuts.
  
- I personally prefer option 2, but many folks prefer option 1.

## Toggling Between Multiple Windows

- Windows and ubuntu:
  - While holding down "Alt", press "Tab" repeatedly until you make the desired selection.
- Mac
  - While holding down "Command", press "Tab" repeatedly until you make the desired selection.
  
## Toggling Between Multiple Desktops.

- Windows:
  - Create a new desktop with Ctrl+Windows+d
  - Toggle between desktops with Ctrl+Windows+Arrows
- Ubuntu:
  - Toggle between desktops with Ctrl+Alt+Arrows
- Mac:
  - The software controlling desktops is called "Mission Control"
  - Hit "F3" to enter Misson Control
  - Use Control+Arrows to move to different desktops.
  
# Quake-style terminal

- I do not personally like the R Studio terminal. It's a little buggy and less efficient to toggle to. 

- Other terminals can also provide more advanced features that make your life easier as you grow your computational skills.

- I use the terminal all the time, so I prefer a Quake-style dropdown menu (named after the Quake video game).

- You can try out Quake-style menus on the various platforms with:

- Linux: Guake <http://guake-project.org/>
- Windows: ConEmu <https://conemu.github.io/>
  - <https://conemu.github.io/en/SettingsQuake.html>
- Mac: iTerm2 <https://www.iterm2.com/>
  - <http://www.karam.io/2018/Turning-iTerm-in-to-a-Quake-style-terminal-on-Mac-OS/>
  
