---
title: "Final Project"
author: "David Gerard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Important Dates
    
- Important Dates:
    - 10/08/2020 at 5:30 PM: Teams and datasets are chosen.
    - 11/12/2020 at 5:30 PM: Progress Report Due.
    - 12/07/2020 at 5:30 PM: Shiny apps, video presentations, and written reports (for graduate students) due.

# Grade Breakdown

50 pts total:

- Undergraduate Students (413)
    - (5 pts) Team and data selection.
    - (5 pts) Progress report.
    - (10 pts) GitHub repo.
    - (20 pts) Shiny App
    - (10 pts) Video Presentation
    
- Graduate Students (613)
    - (5 pts) Team and data selection.
    - (5 pts) Progress report.
    - (10 pts) GitHub repo.
    - (10 pts) Shiny App.
    - (10 pts) Statistical analysis written report.
    - (10 pts) Video Presentation.

# General Description

- The final project consists of a real data analysis, culminating in presenting the results of your analysis in the form of a Shiny App.

- For graduate students, each **individual** will have to also submit a report detailing a statistical analysis concerning the selected project. That is, the written report is *not* a group activity.
  
- You will choose a dataset to analyze. Based on the results of the analysis, you will choose what to present in your Shiny App. 

# (5 pts) Team and Data Selection

- For the final project you will work in groups of size 2 (minimum) or 3 (maximum). 

- Below are some possible sources for data. Each dataset may only be used by one group.

- If you have had a class with me before using these datasets, then you must choose a different dataset to analyze.

- Please email me your dataset choice, along with your group members.

- I will accept other sources as long as they are comparably large and complicated. For example, there are many open data portals from state agencies (<https://opendata.dc.gov/>).

- Lots of API's to cool datasets can be found here: <https://github.com/public-apis/public-apis>

- I will not accept small curated datasets, or those that come from a paper where the data has already been analyzed.

- I will not accept any data that is too clean. For example, I will not accept any data obtained from Kaggle.
  
- You should not select a dataset that you have used before, or are currently using in another class.

- Datasets:

    - Federal bridge inspections from the Federal Highway Admin: 
    
        <https://www.fhwa.dot.gov/bridge/nbi/ascii.cfm>
        
    - Drinking water EPA data: 
    
        <https://www.epa.gov/ground-water-and-drinking-water/drinking-water-data-and-reports>
    
    - Contracts or grants from USA Spending: 
    
        <https://www.usaspending.gov/#/>
    
    <!-- - DC Crime incident data from the DC police:  -->

    <!--     <https://mpdc.dc.gov/page/statistics-and-data> -->
    
    <!-- - SBA disaster loans from the Small Business Administration:  -->

    <!--     <https://www.sba.gov/offices/headquarters/oda/resources/1407821> -->
    
    - Fatal accidents from the NHTSA: 
    
        <https://www.nhtsa.gov/research-data/fatality-analysis-reporting-system-fars>
    
    <!-- - Baltimore crime data from the Baltimore police:  -->

    <!--     <https://www.baltimorepolice.org/crime-stats/open-data> -->
    
    - Aircraft animal strikes from the FAA: 
    
        <https://wildlife.faa.gov/databaseSearch.aspx>
    
    - Bank health data from the FDIC (also see banktracker at IRW):
    
        <https://www.fdic.gov/bank/statistical/guide/data.html>
    
    - WMATA elevators and escalators from the WMATA: 
    
        <http://data.codefordc.org/dataset/wmata-escalators-elevators-hotcars>
    
    - USGS water quality data from the USGS: 
    
        <https://water.usgs.gov/owq/data.html>
    
    - Prison data: 
    
        <http://www.dc.state.fl.us/pub/obis_request.html>
        
    <!-- - College Scorecard:  -->

    <!--     <https://catalog.data.gov/dataset/college-scorecard> -->
        
    - Reporting Carrier On-Time Performance (1987-present) from the Bureau of 
      Transportation Statistics:
    
        <https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236>
        
    - The General Social Survey from the non-partisan and objective research organization at the University of Chicago (NORC):
    
        <https://gssdataexplorer.norc.org/>
        
    - FBI National Incident-Based Reporting System (NIBRS) 
    
        <https://crime-data-explorer.fr.cloud.gov/downloads-and-docs>
        
    - World Bank Country-level Statistics
    
        <https://databank.worldbank.org/>
        
    - O*NET database on work/worker characteristics:
    
        <https://www.onetcenter.org/database.html#individual-files>
        
    - Google trends
      
        <https://trends.google.com/trends/>
        
        <https://cran.r-project.org/package=gtrendsR>

    - eBird database
    
        <https://ebird.org/science/download-ebird-data-products>
        
        <https://cran.r-project.org/package=auk>
      
# (5 pts) Progress Report

- Midway through the semester, I will look at your GitHub repo to make sure
  that you are making progress.
  
- You will be graded on the following:
    - Datasets are downloaded and placed in the data folder.
    - Initial explorations have occurred in the analysis folder. These
      should include plots and summary statistics.

- Additionally, you should place in the analysis folder a document that
  describes:
    - What additional analyses will you perform?
    - What are some tentative ideas for your Shiny app?
    
- You should call this document "TODO.md".

  
# (Undergrad: 20 pts) or (Grad: 10 pts) Shiny App

You will be graded on the complexity of your app, the complexity of the analysis,
and **how well the reactive elements improve your data presentation**.

- Examples for what reactive elements improve:
    - Highly improves: 
        - Change a plot based on the time the units were collected, 
          demonstrating an evolving relationship between variables.
        - Plot data according to the different levels of a categorical variable
          to better explore multidimensional relationships.
    - Moderately improves: 
        - Selecting variables to plot.
        - Changing bin width of a histogram to look at different
          scales of the distribution.
        - Demonstrating how variable transformations result in
          linear relationships.
    - Does not improve: 
        - Delayed evaluation where the evaluation would be
          instantaneous anyway.

Your Shiny app should contain all of the following elements:

- A sophisticated and visually pleasing layout.
- Reactive elements that improve the presentation of results.
- At least one statistical inference procedure ($t$-tests, simple linear 
  regressions, ANOVA, etc).
- Interactive graphics.
- Modified HTML elements.
- You should not be doing intensive data cleaning inside your shiny app. 
  Your shiny app should use cleaned datasets that were cleaned by scripts in
  your analysis folder.

# (10 pts) Presentation

- Each group should showcase their Shiny app with a 15 minute video presentation. I will post these on Blackboard so that your colleagues can see all the cool things you've been up to!

- This presentation should **not** contain any slides, just the Shiny app.

- You should present the conclusions of your analysis using your Shiny app by interactively showing the class the results that you've found.
  
- Each group member should talk for a proportionate amount of time. So if there are two group members, each one should speak for about 7 or 8 minutes. If there are three group members, each one should speak for about 5 minutes.

- My favorite software for recording is OBS Studio: <https://obsproject.com/>. But you can use whatever is most comfortable for you.

- I usually use Kdenlive when I edit my videos: <https://kdenlive.org/en/>

- Please save your video in MP4 Format

# (10 pts) GitHub Repo

- Each group will share a single GitHub repo. What work was done by whom will be viewable in the commit history in the repo.
  
- Your repo will consist of the following folders:
  - app: The location of the Shiny app.
  - analysis: Analysis scripts and Rmd files used to clean and explore data.
  - data: Location of raw, unmodified datasets.
  - output: Location of modified datasets.
  - reports: Location where graduate students place their final project reports.
  
- You will be graded on:
  - Frequency of commits. (2 pts)
      - Do you just commit whole files (bad), or do you commit each time you make significant progress (good)?
  - Division of labor. (1.5 pt)
      - Is there one person doing all of the work (bad) or do all group members contribute (good)?
  - Intermediate results. (1.5 pt)
      - Do you save cleaned data to the output folder to be used later (good) or do you re-clean the dataset each time you open up an analysis file (bad)?
  - Detailed analyses. (3 pts)
      - Do you have all of your analyses in one big mega file (bad) or do you split up your analyses into small analysis files in the analysis folder that perform specific tasks (good)?
      - You should create a bunch of small Rmd files that run small analyses to answer some small question. At a minimum, I expect each person to have two Rmd analysis files.
      - I provided an example analysis in the template repo to give you a sense of what I am expecting. It can be a bit smaller than that, though.
      - Each code block should be prefaced with why you are running that code. Describe your analyses in plain English.
  - Informative README (2 pts)
      - Does your README file contain an informative title? Does it briefly describe the goals of the project? An example README file is presented in the template repo.
  
# (Grad: 10 pts) Statistical Report

- Each graduate student (those taking STAT 613 for credit) should also prepare a written report detailing a statistical analysis concerning their data. This is an individual report, not a group report. Though you can obtain feedback from your group members.

- Your report should consist of the following
  1. An introductory paragraph detailing *in plain English* your question of interest and why this is interesting.
  2. A few paragraphs with accompanying graphics and summary statistics detailing an exploratory data analysis to informally answer your scientific question of interest.
  3. A paragraph transforming your scientific question into a formal statistical hypothesis, using notation where appropriate.
  4. A few paragraphs implementing your statistical analysis. You should include graphics to check modeling assumptions.
  5. A concluding paragraph.
  
- You should write this in R Markdown. It should not be more than 4 pages of text using the default settings (figures and tables do not count against the page limit).

- You should submit your report on GitHub in a folder called "reports".
